### ISSUE TITLE
Program Execution Using Jar or HTML

### ISSUE THREAD

**Issue by bwwagner** [bwwagner/ALytlePokerGame#1]
As the program stands, the HTML needs an extra plugin to run on Edge, Firefox, and Chrome.  I don't think we'll have the security privileges to install the plugin so we need to discuss that with Professor Doyle.

When I run the .jar file the game says Winner in white on a grey background (i.e. the assets aren't loading) and the game will not start a new hand.  If we go this route for demonstration we'll have to come up with a lightweight installation solution.  Maybe we could have the assets in the same directory as the .jar?

**Comment by jrlytle** [comment]
That might work. When I ran the program I had everything mapped out on my Flash Drive. Since they were moved to github, that messed things up a little.

**Comment by bwwagner** [comment]
[Create a JAR](http://stackoverflow.com/questions/9681876/how-to-create-a-jar-file-in-netbeans)

**Comment by bwwagner** [comment]
The JAR is only launching a client that attempts a connection and displays the background at the moment.  I haven't been able to get it to open a server instance using the JAR.

**Comment by bwwagner** [comment]
I am having issues creating a new JAR because the school's version of Java is different from mine.
