### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by bwwagner** [bwwagner/ALytlePokerGame#2]
I added the current draft of the proposal to a newly created Docs directory.  I will continue to edit it from there, but the basics are all there.

Let me know what you think.

**Comment by jrlytle** [comment]
Looks great. It looks like you covered everything pretty well. Now we just have to pass Dr. Doyle's scrutiny.

**Comment by bwwagner** [comment]
Ok.  I'll do a final revision tomorrow and submit it.

**Comment by bwwagner** [comment]
Project Approved!
Feedback from Dr. Doyle on the proposal is:
You may not wholesale download a server (poker). You'll need to do some client and server network programming. Otherwise, project approved.
